# Define the services/containers to be run
services:
  frontend:
    build:
      context: "./client"
    ports:
      - 4200:80
    networks:
      - website_net
  backend:
    build:
      context: "./server"
    ports:
      - 5200:5200
    networks:
      - website_net
  nginx:
    image: nginx:stable-alpine
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.connpf
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    volumes:
      - ./data/nginx:/etc/nginx/conf.d/:ro
      - ./data/certbot/conf:/etc/letsencrypt/:rw
      - ./data/certbot/www:/var/www/certbot/:rw
    ports:
      - 80:80
      - 443:443
    networks:
      - website_net
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot:latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt/:rw
      - ./data/certbot/www:/var/www/certbot/:rw
    networks:
      - website_net

networks:
  website_net:
